version: "3.8"

networks:
  gateway:

services:

  php-fpm:
    networks:
      - gateway
    image: ${REGISTRY}/gateway_api:php-fpm_${IMAGE_TAG}
    restart: always
    links:
      - mysql

  mysql:
    networks:
      - gateway
    image: ${REGISTRY}/gateway_api:mysql_${IMAGE_TAG}
    restart: always
    ports:
      - "33062:3306"
    volumes:
      - ./db_dump:/var/lib/mysql
