version: "3"

networks:
  gateway:

services:

  nginx:
    networks:
      - gateway
    build:
      context: docker/development/nginx
    ports:
      - "8098:80"
    volumes:
      - ./:/var/www/app
    depends_on:
      - php-fpm

  php-fpm:
    networks:
      - gateway
    build:
      context: docker/development/php-fpm
    volumes:
      - ./:/var/www/app
    links:
      - mysql

  mysql:
    networks:
      - gateway
    build:
      context: docker/development/mysql
    ports:
      - "33062:3306"
    volumes:
      - ./db_dump:/var/lib/mysql
